name: Greetings

on: [pull_request_target, issues]

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@fb2402657b4a28582200150d0a145671d0e50597 # v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for opening your first issue! We'll take a look shortly."
        pr-message: "Thanks for your first pull request! We'll review it soon."
